INSERT INTO `location` (`id`, `city`, `province`) VALUES
(1, 'Nivelles', 'Brabant Wallon'),
(2, 'Ath', 'Hainaut'),
(3, 'Charleroi', 'Hainaut'),
(4, 'Mons', 'Hainaut'),
(5, 'Mouscron', 'Hainaut'),
(6, 'Soignies', 'Hainaut'),
(7, 'Thuin', 'Hainaut'),
(8, 'Tournai', 'Hainaut'),
(9, 'Huy', 'Liège'),
(10, 'Liège', 'Liège'),
(11, 'Verviers', 'Liège'),
(12, 'Waremme', 'Liège'),
(13, 'Arlon', 'Luxembourg'),
(14, 'Bastogne', 'Luxembourg'),
(15, 'Marche-en-Famenne', 'Luxembourg'),
(16, 'Neufchateau', 'Luxembourg'),
(17, 'Virton', 'Luxembourg'),
(18, 'Dinant', 'Namur'),
(19, 'Namur', 'Namur'),
(20, 'Philippeville', 'Namur');
